name: "Cypress E2E Tests"

on:
  push:
    branches: ["main"]

jobs:
  cypress-test:
    runs-on: ubuntu-latest

    env:
      NEXT_PUBLIC_APP_URL: ${{ secrets.NEXT_PUBLIC_APP_URL }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      BETTER_AUTH_URL: ${{ secrets.BETTER_AUTH_URL }}
      BETTER_AUTH_SECRET: ${{ secrets.BETTER_AUTH_SECRET }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20.9.0

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          build: npm run build
          start: npm run start
          wait-on: "http://localhost:3000"
